### ISSUE TITLE
nice package. would you release 1.0.0?

### ISSUE THREAD

**Issue by chadxz** [mattyod/deep-has#1]
Hey, this is a nice little package that does it's job well. Would you consider releasing a 1.0.0 version? The api looks stable (hasn't changed in 3 years) so I can't think of any reason not to.

**Comment by mattyod** [comment]
I don't see why not, I guess we could consider it stable by now :) I'll try and grab a moment to do so in the week but otherwise feel free to bump version, perhaps update dependencies and submit a PR.

**Comment by chadxz** [comment]
submitted #2 to update dependencies, bump version and do some cleanup. Would still need a git tag and an npm release. Thanks for being open to 1.0 release!

**Comment by mattyod** [comment]
Done, thanks for the PR and general spring clean.

**Comment by chadxz** [comment]
You're welcome :)
